# Init jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export DOCKER_REGISTRY=reldocker.tibco.com
export DOCKER_REGISTRY_USERNAME=nwang
export DOCKER_REGISTRY_PASSWORD=Tibco20173


alias aira="aria2c --conf-path=/Users/neng/config/aria2.conf -D"

#Common command
alias s="source ~/.bash_profile"
alias l='ls -rtl'
alias ll='ls -rtl'
alias gf='find . -name "*" -print | xargs grep'
alias fn='find . -name '
alias jv='jar tvf '
alias tv='tar tvf '
alias jm='jar cvfM '
alias jx='jar xvf '
alias tx='jar xvf '
alias adc='ant distclean'
alias b="cd .."
alias o='open .'
alias gos='cd /Users/neng/work/svn'
alias sl='svn log -l'
alias np=\''/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'\'
alias nph="np /etc/hosts"
alias npb="np ~/.bash_profile"

#For vagrant
alias vua="vagrant up controller tciservices1 exttenant tciapps1"
alias vu="vagrant up"
alias vd="vagrant destroy"
alias vh='vagrant halt'
alias vs='vagrant global-status'
alias vss='vagrant ssh'

#For docker
alias dcr='docker container run -it '
alias drm='docker image rm -f'
alias di='docker images'
alias drm2='docker rmi $(docker images -q) -f'
alias drc='docker container rm -f'
alias drc2='docker rm $(docker ps -a -q)'
alias di2='docker images -f dangling=true -q'

alias rel='telnet 10.106.129.165'
alias ru2='ssh rubuild2.na.tibco.com -l mqian'
alias ru1='ssh rubuild1.na.tibco.com -l mqian'
alias gc='git config --get remote.origin.url'
alias gb='gradle bootRun'
alias gs='git status'
alias greset='git reset --hard HEAD'
alias glv='git log --stat'
alias gl2='git log -p -2'
alias gln='git log -p -10'
alias gm='git commit -m '
alias slv='svn log -v . | more'
alias suu='svn up'
alias sm='svn commit -m '
alias svs='svn status'
alias adc='ant distclean'
alias dm='cd /Users/tibco/git-repos/domain-server'
alias gr='cd /Users/tibco/clarity/clarity-dev'
alias gr3='cd /Users/tibco/clarity/clarity-3.0.1'
alias cl='cd /Users/tibco/clarity/clarity-dev/build/linux/clarity/3.1'
alias cl3='cd /Users/tibco/clarity/clarity-3.0.1/build/linux/clarity/3.0'
alias am='cd /Users/tibco/git-repos/automation'

#ssh
alias spi='ssh pi@192.168.0.185'
alias snas='ssh admin@192.168.0.209'

